# Numpy Exercise

### 1. 
Create a one-dimensional array with range 2 to 5  elements; Create a 2 by 4 two-dimensional array with range 2 to 9; Create a 4 by 3 by 2 three-dimensional array with range 0 to 23.

Print their properties: shape, dimension, size, and data type.

Solution:

In [10]:
import numpy as np
a = np.arange(2, 6)
print("Array a")
print(a)
print("Array a shape")
print(a.shape)
print("Array a ndims")
print(a.ndim)
print("Array a size")
print(a.size)     
print("Array a dtype")
print(a.dtype)       

b = np.arange(2,10)
b.shape = 2,4
print("\nArray b")
print(b)
print("Array b shape")
print(b.shape)
print("Array b ndims")
print(b.ndim)
print("Array b size")
print(b.size)     
print("Array b dtype")
print(b.dtype)          

c = np.arange(0,24)
c.shape = 4,3,2
print("\nArray c")
print(c)
print("Array c shape")
print(c.shape)
print("Array c ndims")
print(c.ndim)
print("Array c size")
print(c.size)     
print("Array c dtype")
print(c.dtype)      

Array a
[2 3 4 5]
Array a shape
(4,)
Array a ndims
1
Array a size
4
Array a dtype
int32

Array b
[[2 3 4 5]
 [6 7 8 9]]
Array b shape
(2, 4)
Array b ndims
2
Array b size
8
Array b dtype
int32

Array c
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
Array c shape
(4, 3, 2)
Array c ndims
3
Array c size
24
Array c dtype
int32


### 2.
Create an array [1, 2, 3, 4] and convert the elements' data type to float. So in printing, it is showing [1., 2., 3., 4.]; 
also, print the reverse order of the array. Finally, change this row vector to a 4 by 1 array.
(Hint: numpy.asfarray() and [::-1], [:, np.newaxis]/[:, -1])

Creat a 5 by 5 array with 1 on the border (first and last row, first and last column) and 0 inside;
(Hint: numpy.ones() and array slicing)

*Create a 3 by 3 array with 1 and add border with 0, as the array will become 4 by 4
(Hint: numpy.pad())

Create a 8 by 8 matrix and fill it with a checkerboard pattern, use 0 to represent white and 1 to represent black.
(Hint: array slicing)


Solution:

In [15]:
d = np.arange(1,5, dtype=float)
print("Array")

print(d)

print("\nArray Reversed")
print(d[::-1])

print("\nArray as 4 by 1")
d1 = d[:,np.newaxis]
print(d1)

print("\n5 by 5 Array")

e = np.ones((5,5))
e[1:4,1:4] = 0
print(e)

print("\n3 by 3 Array")

f = np.ones((3,3))
f1 = np.pad(f, (1,1), "constant", constant_values=0)
print(f1)

print("\n8 by 8 array")
g = np.ones((8,8))
g[0:9:2, 0:9:2] = 0
g[1:9:2, 1:9:2] = 0
print(g)

Array
[1. 2. 3. 4.]

Array Reversed
[4. 3. 2. 1.]

Array as 4 by 1
[[1.]
 [2.]
 [3.]
 [4.]]

5 by 5 Array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

3 by 3 Array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

8 by 8 array
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 3.
Create an array from 0 to 9 and extract the even elements for printing; then replace these elements by -1.
(Hint: use boolean index and element-wise comparison)

Create two arrays: x = [5,6,7,8,3,4] and y = [5,3,4,5,2,4], find the positions of the same elements in the two array.
(Hint: np.where() and element-wise comparison)

Create two arrays: [0, 10, 20, 40, 60] and [0, 40]. test whether each element of x is also present in y.
(Hint: np.isin() and use the two arrays as input)

Solution:

In [19]:
h = np.arange(0,10)
print("Original Array")
print(h)

print("\nEven")
print(h[0:9:2])

print("\nEven Replaced by -1")

h[0:9:2] = -1
print(h)

print("\nArray x")
x = np.array([5,6,7,8,3,4])
print(x)

print("\nArray y")
y = np.array([5,3,4,5,2,4])
print(y)

print("\n")
for el in x:
    print(str(el) + str(np.where(el == y)))
print("\n")

i = [0, 10, 20, 40, 60]
j = [0, 40]
print(np.isin(i,j))

Original Array
[0 1 2 3 4 5 6 7 8 9]

Even
[0 2 4 6 8]

Even Replaced by -1
[-1  1 -1  3 -1  5 -1  7 -1  9]

Array x
[5 6 7 8 3 4]

Array y
[5 3 4 5 2 4]


5(array([0, 3], dtype=int64),)
6(array([], dtype=int64),)
7(array([], dtype=int64),)
8(array([], dtype=int64),)
3(array([1], dtype=int64),)
4(array([2, 5], dtype=int64),)


[ True False False  True False]


### 4.
Creat an one-dimensional array to hold 24 random integer numbers between 0 and 100, then do the following:

1. Find the position of minimum and maximum;
2. Reshape it into 6 by 4 array; 
3. Sort the array along axis 0;
4. Calculate mean, average, std of the array along axis = 0;
5. Reshape it into 4 by 3 by 2 and print the new view;
6. Transpose the array in step 5;
7. Save the file into a text output file "data.csv" with the delimiter = ','.
(Hint: x is a 3D array, you can not directly use `np.savetxt` to save it, you have to iterate over the last axis to slice the array and save.)

Solution:

In [23]:
## Your program starts here
np.random.seed(5)
k = np.random.randint(0, 101, 24)
print("Array")
print(k)
print("\n")

print("Minimum position: " + str(np.where(k == min(k))[0][0]))
print("Maximum position: " + str(np.where(k == max(k))[0][0]))

print("\nReshaped")
k = np.reshape(k, (6,4))
print(k)

print("\nSorted along axis 0")
k.sort( axis = 0)
print(k)

print("\nMean, average and standard deviation")
print(np.mean(k, axis = 0))
print(np.average(k, axis = 0))
print(np.std(k, axis = 0))

print("\nReshaped to 4 by 3 by 2")
k = np.reshape(k, (4,3,2))
print(k)

k = np.transpose(k)
print("\nTransposed")
print(k)

print("\n")
print(k[:,:,:5])
 
# for x in k:
#     np.savetxt("data.cdv", x, delimiter = ",")
np.savetxt("data.csv", np.reshape(k, (3,-1)), delimiter = ",")
print("\nSaved into data.csv")

Array
[ 99  78  61  16  73   8 100  62  27  30  80   7  76  15  53  80  27  44
  77  75  65  47  30  84]


Minimum position: 11
Maximum position: 6

Reshaped
[[ 99  78  61  16]
 [ 73   8 100  62]
 [ 27  30  80   7]
 [ 76  15  53  80]
 [ 27  44  77  75]
 [ 65  47  30  84]]

Sorted along axis 0
[[ 27   8  30   7]
 [ 27  15  53  16]
 [ 65  30  61  62]
 [ 73  44  77  75]
 [ 76  47  80  80]
 [ 99  78 100  84]]

Mean, average and standard deviation
[61.16666667 37.         66.83333333 54.        ]
[61.16666667 37.         66.83333333 54.        ]
[26.27049464 23.10844002 22.20673071 30.91385881]

Reshaped to 4 by 3 by 2
[[[ 27   8]
  [ 30   7]
  [ 27  15]]

 [[ 53  16]
  [ 65  30]
  [ 61  62]]

 [[ 73  44]
  [ 77  75]
  [ 76  47]]

 [[ 80  80]
  [ 99  78]
  [100  84]]]

Transposed
[[[ 27  53  73  80]
  [ 30  65  77  99]
  [ 27  61  76 100]]

 [[  8  16  44  80]
  [  7  30  75  78]
  [ 15  62  47  84]]]


[[[ 27  53  73  80]
  [ 30  65  77  99]
  [ 27  61  76 100]]

 [[  8  16  44  80]
  [  7

### 5.
Creat an one-dimensional array with this code:
`a = np.linspace(1,48,48).reshape(3,4,4)`

Index or slice this array to obtain the following:

(a) $20.$

(b) $ [  9. \hspace{0.25em} 10. \hspace{0.25em} 11. \hspace{0.25em}  12.] $

(c) 
$
  [[ 33. \hspace{0.25em} 34. \hspace{0.25em} 35.\hspace{0.25em}  36.] \\
   [ 37. \hspace{0.25em} 38. \hspace{0.25em} 39.\hspace{0.25em}  40.] \\
   [ 41. \hspace{0.25em} 42. \hspace{0.25em} 43.\hspace{0.25em}  44.] \\
   [ 45. \hspace{0.25em} 46. \hspace{0.25em} 47.\hspace{0.25em}  48.]]
$

(d) 
$
[[  5., \hspace{0.25em}  6.],\\
 [ 21., \hspace{0.25em} 22.],\\
 [ 37., \hspace{0.25em} 38.]]
$

(e)
$
[[ 36.\hspace{0.25em}  35.] \\
 [ 40.\hspace{0.25em}  39.] \\
 [ 44.\hspace{0.25em}  43.] \\
 [ 48.\hspace{0.25em}  47.]]
$

Solution:

In [3]:
### Your program starts here
a = np.linspace(1,48,48).reshape(3,4,4)
print("Original")
print(a)

print("\n")
print("(a)")
print(a[1][0][3])

print("\n")
print("(b)")
print(a[0][2])

print("\n")
print("(c)")
print(a[2])

print("\n(d)")
print(a[:,1,0:2])

print("\n(e)")
print(a[2,:,::-1][:,0:2])

Original
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]

 [[17. 18. 19. 20.]
  [21. 22. 23. 24.]
  [25. 26. 27. 28.]
  [29. 30. 31. 32.]]

 [[33. 34. 35. 36.]
  [37. 38. 39. 40.]
  [41. 42. 43. 44.]
  [45. 46. 47. 48.]]]


(a)
20.0


(b)
[ 9. 10. 11. 12.]


(c)
[[33. 34. 35. 36.]
 [37. 38. 39. 40.]
 [41. 42. 43. 44.]
 [45. 46. 47. 48.]]

(d)
[[ 5.  6.]
 [21. 22.]
 [37. 38.]]


(e)
[[36. 35.]
 [40. 39.]
 [44. 43.]
 [48. 47.]]


### 6.

Create two arrays by the codes:

`array1 = np.arange(20).reshape(4,5)`

`array2 = np.array([[1,2,np.nan],[4,5,6],[np.nan, 7, np.nan]])`

Test if elements in arrray1 and array2 are all evaluated to `True` by `np.all()`.

Test if any element in array1 and array 2 is evaluated to `True` by `np.any()`.

Then replace all the `np.nan` in array2 by the mean of array1. (Hint: use `np.isnan()` to test array2 first)



In [27]:
##Your program starts here


array1 = np.arange(20).reshape(4,5)
print("array1")
print(array1)
array2 = np.array([[1,2,np.nan],[4,5,6],[np.nan, 7, np.nan]])
print("\narray2")
print(array2)

print("\nEvaluating array1 with np.all")
print(np.all(array1))
print("\nEvaluating array2 with np.all")
print(np.all(array2))

print("\nEvaluating array1 with np.any")
print(np.any(array1))
print("\nEvaluating array2 with np.any")
print(np.any(array2))

print("\nCalculating array1 mean")
array1_mean = np.mean(array1)
print(array1_mean)

print("\nReplacing array2 nan with array1 mean")
array2nan = np.isnan(array2)
array2[array2nan] = array1_mean
print(array2)

array1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

array2
[[ 1.  2. nan]
 [ 4.  5.  6.]
 [nan  7. nan]]

Evaluating array1 with np.all
False

Evaluating array2 with np.all
True

Evaluating array1 with np.any
True

Evaluating array2 with np.any
True

Calculating array1 mean
9.5

Replacing array2 nan with array1 mean
[[1.  2.  9.5]
 [4.  5.  6. ]
 [9.5 7.  9.5]]


### 7.

a. Creat an array with 3 by 4 random numbers array within the range of (0, 1). Swap the three rows, that is, row index (0, 1, 2) -> row index (2, 0, 1). Swap first column and third column, that is, column index (0, 1, 2, 3) -> column index (2, 1, 0, 3)



In [28]:
##Your program start here
m = np.random.uniform(0,1,12)
m = np.reshape(m, (3,4))
print("Original:")
print(m)

print("\nSwapping 3 rows")
m[[2,0,1]] = m[[0,1,2]] 
print(m)

print("\nSwapping first and third column")
m[:,[0,1,2,3]] = m[:,[2,1,0,3]]
print(m)

Original:
[[0.20415475 0.11909536 0.87790307 0.52367529]
 [0.492136   0.7318711  0.01458075 0.09336303]
 [0.82655425 0.83349274 0.89241102 0.9580135 ]]

Swapping 3 rows
[[0.492136   0.7318711  0.01458075 0.09336303]
 [0.82655425 0.83349274 0.89241102 0.9580135 ]
 [0.20415475 0.11909536 0.87790307 0.52367529]]

Swapping first and third column
[[0.01458075 0.7318711  0.492136   0.09336303]
 [0.89241102 0.83349274 0.82655425 0.9580135 ]
 [0.87790307 0.11909536 0.20415475 0.52367529]]


### 8.

Iris data is a prototype data set for machine learning beginners in building classfication models. It has five columns: sepallength, sepalwidth, petallength, petalwidth, and species. Data in the first four columns are float type data and the last column is string. Do the work below:

1. Use `genfromtxt()` to read data from the url `'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'` to a numpy array. 

2. Store the numeric values in one array and string values in the other array.

3. Calculate the mean, median, std of the first column, which is sepal length.

4. Normalize the data in the first columns, so that data are in the range of [0, 1]

5. the 5th and 95th percentile of iris's sepallength (the first column)


In [30]:
##Your program starts here
url = "archive.ics.uci.edu\ml\machine-learning-databases\iris\iris.data"
data = np.genfromtxt(url, delimiter=',')
numeric = data[:,0:4]
string = data[:,4]

print("\nCalculating sepal length mean")
print(np.mean(numeric[:,0]))
print("\nCalculating sepal length median")
print(np.median(numeric[:,0]))
print("\nCalculating sepal length stdev")
print(np.std(numeric[:,0]))

colmax, colmin = numeric[:,0].max(), numeric[:,0].min()

norm_numeric  = (numeric[:,0] - colmin)/(colmax - colmin)
print("\nNormalised sepal length")
print(norm_numeric)

print("\n5th and 95th percentile")
print(np.percentile(numeric[:,0], q=[5, 95]))


Calculating sepal length mean
5.843333333333334

Calculating sepal length median
5.8

Calculating sepal length stdev
0.8253012917851409

Normalised sepal length
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.